name: Build and Release server

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    runs-on: build-release

    steps:
    - uses: actions/checkout@v3
    
    - name: "Copy Godot Headless Installation"
      run: cp -r /home/azureuser/Godot_v3.5-stable_mono_linux_headless_64/* .
      
    - name: "Copy config file"
      run: cp config-prod.cfg config.cfg

    - name: "Start tmux instance"
      run: tmux new -d -s runners-gate-server
      
    - name: "[tmux] Build Solution"
      run: tmux send-keys -t runners-gate-server ./Godot_v3.5-stable_mono_linux_headless.64 Space --build-solutions Enter

    - uses: GuillaumeFalourd/wait-sleep-action@v1
      with:
        time: '10' # 10 Seconds

    - name: "[tmux] Cancel build"
      run: tmux send-keys -t runners-gate-server C-c

    - name: "[tmux] Start game server"
      run: tmux send-keys -t runners-gate-server ./Godot_v3.5-stable_mono_linux_headless.64 Space . Enter
