name: Build and Release server

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: build-release

    steps:
    - uses: actions/checkout@v3
    
    - name: Copy Godot Headless Installation
      run: cp -r /home/azureuser/Godot_v3.5-stable_mono_linux_headless_64/* .
      
    - name: Copy config file
      run: cp config-prod.cfg config.cfg

    - name: Build Solution
      run: ./Godot_v3.5-stable_mono_linux_headless.64 --build-solutions

    - name: Start Game Server in tmux
      run: tmux new -d -s runners-gate-server; tmux send-keys -t runners-gate-server ./Godot_v3.5-stable_mono_linux_headless.64 . Enter
