name: Build and Release server

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: build-release

    steps:
    - uses: actions/checkout@v3
    
    - name: Copy Godot Headless Installation
      run: cp -r /home/azureuser/Godot_v3.5-stable_mono_linux_headless_64/* .
      
#    - name: Copy Godot Server Installation
#      run: cp -r /home/azureuser/Godot_v3.5-stable_mono_linux_server_64/ .

    - name: Build Solution
      run: ./Godot_v3.5-stable_mono_linux_headless.64 --build-solutions

    - name: Start Game Server in tmux
      run: tmux new -s session_name; tmux send-keys -t session_name "cd runners-gate-server; ./Godot_v3.5-stable_mono_linux_headless.64 ."
